import { defineFeature } from '../definition';

export const toolsImageBinary = defineFeature({
  id: 'tools-image-binary',
  name: 'Image & Binary File Context',
  category: 'Tools',
  description:
    'Attach screenshots, diagrams, and binary files to Copilot Chat so agents can analyze them natively — useful for debugging UI issues, understanding visual designs, and reading binary data.',
  docsURL: 'https://code.visualstudio.com/docs/copilot/chat/copilot-chat',
  detectHints: ['chat.imageCarousel.enabled', 'imageCarousel', 'binary file', 'hexdump'],
  impact: 'medium',
  difficulty: 'low',
  setupSteps: [
    'In the Chat input, click the attachment button (paperclip icon) and choose an image or binary file.',
    'Alternatively, drag and drop an image directly into the Chat panel, or paste from clipboard.',
    'Ask Copilot to analyze it, e.g. "What is wrong in this screenshot?" or "Parse this binary file."',
    'Enable `chat.imageCarousel.enabled` to view agent-generated images in a browseable carousel.',
  ],
  tutorialPrompt: `I'd like to learn how to use image and binary file attachments in GitHub Copilot Chat.

Please help me understand this feature by:
1. What image and binary file support means:
   - Attaching screenshots, diagrams, and binary files to chat requests
   - How agents can analyze images visually (UI screenshots, error dialogs, diagrams)
   - How binary files are presented to the agent (hexdump format)
2. How to attach files:
   - Using the paperclip attachment button in the chat input
   - Dragging and dropping images directly into the Chat panel
   - Pasting images from clipboard
3. Common use cases:
   - Sharing a screenshot of a UI bug for the agent to diagnose
   - Attaching a design mockup and asking the agent to generate matching code
   - Providing binary data for the agent to parse or interpret
4. The image carousel:
   - Enabling \`chat.imageCarousel.enabled\` to browse images from the session
   - Navigating between images generated by tool calls

Show me examples using my actual workspace.`,
  addedIn: '1.112.0',
});
