name: Get latest versions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get version
        